import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const merriweather = localFont({
  src: "./fonts/Merriweather.ttf",
  variable: "--font-merriweather",
  weight: "100 900",
});
const merriweatherBold = localFont({
  src: "./fonts/Merriweather-Bold.ttf",
  variable: "--font-merriweather-bold",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#E5E5E5] ${geistSans.variable} ${merriweather.variable} ${merriweatherBold.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
