import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const brodies = localFont({
  src: "./fonts/brodies.ttf",
  variable: "--font-brodies",
  weight: "100 900",
});
const mermaid1001 = localFont({
  src: "./fonts/Mermaid1001.ttf",
  variable: "--font-mermaid1001",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#E5E5E5] ${geistSans.variable} ${geistMono.variable} ${brodies.variable} ${mermaid1001.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
